version: '3.8'

services:
  backend:
    build: ./CodeSphereStudio
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - GROQ_API_KEY=${GROQ_API_KEY}
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/codesphere
    deploy:
      resources:
        limits:
          memory: 1G
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - codesphere-network

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    deploy:
      resources:
        limits:
          memory: 512M
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - codesphere-network

  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=codesphere
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - codesphere-network

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - codesphere-network

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - codesphere-network

volumes:
  postgres-data:

networks:
  codesphere-network:
    driver: bridge
