global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'codesphere-backend'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['backend:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']